# .github/workflows/issue-classifier.yml
name: Issue classifier

on:
  issues:
    types: [opened, edited]

jobs:
  classify:
    runs-on: ubuntu-latest
    name: Classify issue
    steps:
      - name: Classify issue
        uses: plopcas/emoji-issue-classifier@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
