# .github/workflows/issue-classifier.yml
name: 'Use Emoji Issue Classifier Action'

on:
  issues:
    types: [opened, edited]

jobs:
  classify:
    runs-on: ubuntu-latest

    steps:
    - name: Use Emoji Classifier
      uses: plopcas/emoji-issue-classifier@v1.0.19
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
