# .github/workflows/issue-classifier.yml
name: 'Use Emoji Issue Classifier Action'

on:
  issues:
    types: [opened, edited]

jobs:
  classify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Emoji Classifier
      uses: plopcas/emoji-issue-classifier@v1.0.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

